function [fitresult, gof] = createFit(d)
%CREATEFIT(D)
%  Create a fit.
%
%  Data for 'IPSC fit double' fit:
%      Y Output: d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Mar-2017 09:47:38


%% Fit: 'IPSC fit double'.
[xData, yData] = prepareCurveData( [], d );

% Set up fittype and options.
ft = fittype( 'a1*exp(-t/tau1) + a2*exp(-t/tau2)', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [20 10 100 200];
opts.Lower = [0 0 0 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'IPSC fit double' );
h = plot( fitresult, xData, yData );
legend( h, 'd', 'IPSC fit double', 'Location', 'NorthEast' );
% Label axes
ylabel d
grid on


